HW
inventorsoft-academy/spring-rest-task pull request #19
Opened 2022-09-29 23:02 UTC by DenisBratuh

2022-09-30 10:20 UTC, maksym-studenets requested changes
Please resolve the issues

2022-09-30 10:20 UTC, maksym-studenets commented on src/main/java/com/mail/Controllers/EmailController.java
> +    public void setmDao(MessagesDao mDao) {
Use constructor injection whenever possible

2022-09-30 10:20 UTC, maksym-studenets commented on src/main/java/com/mail/Dao/MessagesDao.java
> +                .orElse(null);
null will return a successful status which is not what the client should expect. If I am looking for something specific and cannot find it, the app should fail quickly

2022-09-30 10:20 UTC, maksym-studenets commented on src/main/java/com/mail/Entities/TextMessage.java
> +    public String getTitle() {
Use Lombok annotations to avoid boilerplate

2022-09-30 10:20 UTC, maksym-studenets commented on src/main/java/com/mail/Controllers/EmailController.java
> +package com.mail.Controllers;
Package names should be lowecase only, according to the convention

2022-09-30 10:20 UTC, maksym-studenets commented on pom.xml
> +    <dependency>
You are not using database, so remove data-jpa and postgres

2022-09-30 10:20 UTC, maksym-studenets commented on src/main/java/com/mail/Application.java
> +@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
Remove unnecessary dependencies, and then also this exclude option

2022-09-30 10:20 UTC, maksym-studenets commented on src/main/java/com/mail/Dao/MessagesDao.java
> +        findMessage(id).update(text);
In your current implementation, you will get an unexpected NPE if a message with provided ID is not found

2022-09-30 10:20 UTC, maksym-studenets commented on src/main/java/com/mail/Dao/MessagesDao.java
> +        return mDao.remove(findMessage(id));
Why don't you just traverse the list and delete a message by ID? Even if such an ID is not found, you can just swallow that case. If a client is attempting to delete a non-existent entity, it should not receive an error because his request is already fulfilled in some way

2022-10-04 09:49 UTC, DenisBratuh commented
Updated:)

2022-10-05 13:02 UTC, maksym-studenets approved these changes

2022-10-05 13:02 UTC, maksym-studenets commented on src/main/java/com/mail/Application.java
> +@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
Why is this needed now?

2022-10-05 13:02 UTC, closed without merging